name: app_dictionary
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  mockito: ^5.4.2
  flutter_modular: ^5.0.3
  flutter_bloc: ^8.1.3
  auto_size_text: ^3.0.0
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.0
  salomon_bottom_bar: ^3.3.2
  flutter_svg: ^2.0.7
  flutter_tts: ^3.7.0
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  firebase_auth: ^4.6.3
  internet_connection_checker: ^1.0.0+1
  email_validator: ^2.1.17
  feather_icons: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - .env
    - "assets/"
    - "assets/json/"
    - "assets/json/words_dictionary.json"
    - "assets/images/"
    - "assets/images/no_data.svg"

  #
